import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div>
    
    <div>
      <Head>
        <title>Administrar Vendedores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LOGO.svg" />
      </Head>
   
      <main >
        <Navbar />
      </main>

     
    </div>
    </div>
  )
}
